### ISSUE TITLE
Add reconnection limit

### ISSUE THREAD

**Issue by OssiPesonen** [respectTheCode/node-caspar-cg#21]
This issue was not actually addressed correctly: https://github.com/respectTheCode/node-caspar-cg/issues/7

Please add a reconnection limit to set a maximum number of reconnection attempts made. The server otherwise ends up in an eternal reconnection loop when reconnect is true. When reconnect limit hits, disconnect.

Configuration reconnectInterval adds number of seconds until second attempt is made. It does not however fix original issue.

**Comment by respectTheCode** [comment]
I haven't run into a situation where I wanted it to stop trying to connect. If you want to work on it I will merge a pull request.
