### ISSUE TITLE
Pure AMPC command without prefixes

### ISSUE THREAD

**Issue by OssiPesonen** [respectTheCode/node-caspar-cg#25]
Sorry, this might be more of a question than an issue but does the library have a simple custom command method to call? Every method seems to contain some sort of prefix and I think a method to use a custom command would be helpful in events where people can read the AMPC protocol instructions and create these commands for the server.

**Example**

    ccg.prototype.customCommand = function (cmd) {
        var self = this;
        self.sendCommand(cmd);
    };

**Usage**

    ccg.customCommand('MIXER 1-1 OPACITY 0 30 EASEINSINE');

**Comment by respectTheCode** [comment]
It does. Internally all of the commands go through `ccg.sendCommand`. It takes a string and a callback.

https://github.com/respectTheCode/node-caspar-cg/blob/master/lib/connection.js#L192

**Comment by OssiPesonen** [comment]
Hey, thanks! I totally missed that.
